# Generated by Django 3.1.3 on 2022-01-13 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20220109_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsFeeds',
            new_name='NewsFeed',
        ),
    ]
