# Generated by Django 3.1.3 on 2022-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20220306_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetphoto',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='tweetphoto',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
